name: Create Artifact
on: [push]
jobs:
  Upload:
    name: Upload Artifact
    runs-on: ubuntu-latest
    steps:
      - shell: bash
        run: |
          expr 1 + 1 > output.log
      - name: Upload output file
        uses: actions/upload-artifact@v2
        with:
          name: output-log-file
          path: output.log
  Download:
    name: Download Artifact
    runs-on: ubuntu-latest
    steps:
      - name: Download output file
        uses: actions/download-artifact@v2
        with:
          name: output-log-file
          path: output.log
